[workspace]
members = ["backend-2fa", "stellar-contracts"]
resolver = "2"

[profile.dev]
panic = "unwind"

[profile.test]
panic = "unwind"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
